# Generated by Django 4.0.3 on 2022-03-25 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash', models.CharField(max_length=150)),
                ('url', models.CharField(max_length=1000)),
                ('short_link', models.CharField(max_length=200)),
            ],
        ),
    ]
